version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo_data:
